apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
    spec:
      containers:
      - name: simple-time-container
        image: devyanipatil26/simpletimeservice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: time-service
spec:
  selector:
    app: time-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP